apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-swift-outputs-pvc
spec:
  storageClassName: rook-cephfs  # Keep RWX if needed for multi-node
  accessModes:
    - ReadWriteMany  # Only if you need multi-node access
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi